FactoryBot.define do
  factory :article do
    title { "ALorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at condimentum quam. Vivamus sed posuere tortor, eget ultrices augue" }
    text { "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam massa odio, congue sit amet quam ut, condimentum bibendum quam. Maecenas tincidunt consequat ipsum et rhoncus. Mauris tincidunt ante ex, sit amet imperdiet ligula volutpat nec. In in viverra lacus, viverra commodo sapien. Nunc convallis elit et magna sagittis condimentum. Nulla non nisl a nunc varius maximus. Nullam non efficitur lacus, vitae suscipit dui. Sed vestibulum nisi in gravida egestas. Cras non turpis lectus. Duis in felis sapien. Donec facilisis tincidunt est, eget ullamcorper magna. Vestibulum tincidunt dui id nibh luctus vestibulum. Etiam in rutrum elit, pharetra gravida dui. Mauris quis tincidunt magna. In sed turpis eu arcu sodales hendrerit in et magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Quisque suscipit tortor urna, vel fringilla orci sagittis non. Nulla facilisi. Sed maximus sem odio, sed hendrerit ex iaculis sed. Sed dapibus tellus nec vestibulum ultrices. Etiam auctor purus quis tellus sodales, a suscipit arcu porta. Nam pharetra lectus velit, in sodales risus tincidunt quis. Aliquam suscipit risus sapien, eget facilisis enim fringilla vitae. Morbi eu sem at massa ullamcorper aliquet. Suspendisse potenti. Proin felis leo, viverra ac orci vel, pellentesque finibus dolor.
Ut sagittis odio nec semper efficitur. Aenean pulvinar quam semper eros tristique elementum. Etiam rhoncus lobortis purus, at pulvinar leo luctus tincidunt. Nullam ac facilisis risus. Sed ultricies diam sem, eget venenatis velit commodo nec. Duis turpis quam, pulvinar quis dapibus eget, aliquet nec dui. Donec vitae mauris diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque ligula vel facilisis facilisis. Phasellus sit amet augue turpis. Pellentesque a interdum elit, a faucibus ligula. Fusce ut congue lectus. In porttitor, velit eu imperdiet euismod, nisi nibh mollis neque, sed pulvinar nibh lorem vitae risus. Pellentesque sed convallis libero. Fusce porta est arcu, ut dictum quam consectetur sit amet.
Duis non ipsum facilisis enim pellentesque interdum. Donec vitae justo sed mauris posuere volutpat ac at justo. Vivamus lacinia quam at ex sodales fermentum. Duis porttitor velit at fermentum laoreet. Proin tincidunt ante ac blandit malesuada. Nam ac cursus tortor. Vivamus non volutpat leo. Vivamus dignissim, augue id imperdiet elementum, neque libero placerat justo, et fringilla sem urna ut orci. Vivamus in nisi posuere, consequat ligula sit amet, ultrices sem. Integer molestie nunc quis orci interdum sollicitudin. Ut quis enim nibh. Ut quis porta dui, ut cursus quam. Quisque in est at magna viverra maximus.
Sed cursus molestie turpis, at malesuada arcu tempor ac. Integer nec neque augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc ultrices dui molestie tristique fermentum. Morbi viverra orci vitae tortor vestibulum tincidunt. Phasellus ultrices sagittis sapien non dictum. Sed laoreet mattis elit, at consequat metus fringilla eu. Aliquam vitae ullamcorper arcu. Pellentesque quis mi nec sem fermentum vestibulum. Vivamus eu vehicula odio, sed cursus purus. Ut fringilla nulla pulvinar, semper risus sed, tincidunt nunc. Praesent suscipit efficitur purus sed auctor. Quisque sit amet auctor nibh, eu semper nisl. Quisque convallis massa urna, nec ultrices odio porta non.
Nullam eleifend facilisis est sed porttitor. Aenean ultrices tincidunt nulla, vitae gravida arcu. Duis nec tellus volutpat ante semper semper posuere nec neque. Proin arcu neque, tempor ut tempor ac, rhoncus vel neque. Curabitur aliquam venenatis elit sit amet rhoncus. Cras sed ligula in eros mollis sollicitudin. Nam mattis facilisis mi sed rutrum. Nullam condimentum nibh et justo iaculis, at lobortis justo pretium. Integer et faucibus nunc, in feugiat turpis. Nulla pellentesque ullamcorper pretium.
" }

    # создаем фабрику с названием article_with_comments
    # для создания статьи с несколькими комментариями
    factory :article_with_comments do
      # после создания article
      after :create do |article, evaluator|
        # создаем список из 3-х комментариев
        create_list :comment, 3, article: article
      end
    end
  end
end